ALTER TABLE pmieducar.instituicao ADD COLUMN controlar_espaco_utilizacao_aluno smallint;
ALTER TABLE pmieducar.instituicao ADD COLUMN percentagem_maxima_ocupacao_salas numeric(5, 2);
ALTER TABLE pmieducar.instituicao ADD COLUMN quantidade_alunos_metro_quadrado integer;
ALTER TABLE pmieducar.instituicao ADD COLUMN exigir_vinculo_turma_professor smallint;
ALTER TABLE pmieducar.instituicao ADD COLUMN gerar_historico_transferencia boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN matricula_apenas_bairro_escola boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN restringir_historico_escolar boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN coordenador_transporte varchar;
ALTER TABLE pmieducar.instituicao ADD COLUMN restringir_multiplas_enturmacoes boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN permissao_filtro_abandono_transferencia boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN data_base_matricula date;
ALTER TABLE pmieducar.instituicao ADD COLUMN multiplas_reserva_vaga boolean default false not null;
ALTER TABLE pmieducar.instituicao ADD COLUMN reserva_integral_somente_com_renda boolean default false not null;
ALTER TABLE pmieducar.instituicao ADD COLUMN data_expiracao_reserva_vaga date;
ALTER TABLE pmieducar.instituicao ADD COLUMN data_fechamento date;
ALTER TABLE pmieducar.instituicao ADD COLUMN componente_curricular_turma boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN reprova_dependencia_ano_concluinte boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN controlar_posicao_historicos boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN data_educacenso date;
ALTER TABLE pmieducar.instituicao ADD COLUMN bloqueia_matricula_serie_nao_seguinte boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN permitir_carga_horaria boolean default false;
ALTER TABLE pmieducar.instituicao ADD COLUMN exigir_dados_socioeconomicos boolean default false;
ALTER TABLE pmieducar.instituicao ADD COLUMN altera_atestado_para_declaracao boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN orgao_regional integer;
ALTER TABLE pmieducar.instituicao ADD COLUMN obrigar_campos_censo boolean;
ALTER TABLE pmieducar.instituicao ADD COLUMN obrigar_documento_pessoa boolean default false;