create table modules.lingua_indigena_educacenso
(
  id     integer not null
    constraint lingua_indigena_educacenso_pk
    primary key,
  lingua varchar(255)
);

alter table modules.lingua_indigena_educacenso
  owner to postgres;

INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (30, 'Boróro');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (244, 'Umutína');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (42, 'Guató');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (12, 'Apinayé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (251, 'Canela');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (252, 'Kanéla Apaniekra/Canela Apaniekrã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (205, 'Kanéla Rankocamekra/ Canela Ramkokamekrã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (253, 'Gavião Krikatêjê/ Gavião Krinkatejé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (254, 'Gavião Parkatêjê/ Guató Parakatejé/ Gavião do Pará');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (240, 'Gavião Pukobiyé/ Gavião Pukobié');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (255, 'Krahô/ Crao, Kraô');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (256, 'Krao Kanela');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (223, 'Kreje/ Krenjé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (224, 'Krikatí/ Krinkatí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (257, 'Kokuiregatêjê/ Kokuiregatejje');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (258, 'Timbira');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (235, 'Kaingáng');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (221, 'Mebengokré (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (86, 'Mentuktíre, Txukahamae (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (220, 'Kayapó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (81, 'Gorotire (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (82, 'Kararaô (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (83, 'Kokraimoro (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (84, 'Kubenkrngkegn (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (85, 'Menkrangnoti (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (87, 'Xikrin (Kayapó)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (132, 'Panará, Krenakarôre/ Kren-akarôre');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (150, 'Suyá, Kisêdjê/ Kisedjê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (241, 'Tapayúna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (259, 'Xacriabá/ Xakriabá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (5, 'Xavánte/ Xavante');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (6, 'Xerénte');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (188, 'Xokléng');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (260, 'Jê (não específico)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (63, 'Karajá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (50, 'Javaé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (185, 'Xambioá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (92, 'Krenák');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (107, 'Maxakalí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (261, 'Pataxó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (262, 'Pataxó Hã Hã Hãe/ Pataxó Há-Há-Há');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (129, 'Ofayé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (142, 'Canoeiros/ Rikbaktsá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (192, 'Fulni-ô/ Yathê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (65, 'Karitiána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (23, 'Awetí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (51, 'Jurúna/ Yudjá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (187, 'Xipáya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (106, 'Mawé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (200, 'Arara do Aripuana/ Arara do Aripuanã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (19, 'Aruá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (31, 'Cinta Larga/ Cinta-Larga');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (36, 'Gavião (Ikõro, Digüt), Gavião de Rondônia/ Ikolen');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (197, 'Zoró');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (263, 'Salamãy');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (236, 'Suruí de Rondônia');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (111, 'Mondé, Tupí-Mondé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (112, 'Mundurukú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (96, 'Kuruáya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (141, 'Puruborá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (66, 'Arara de Rondônia/ Káro');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (264, 'Ramaráma');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (265, 'Urucú/ Urucu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (198, 'Akuntsú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (99, 'Makuráp');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (110, 'Sakurabiat/ Kampé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (171, 'Tuparí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (2, 'Ajuru/ Wayoro, Ajurú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (7, 'Amanayé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (11, 'Apiaká');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (17, 'Araweté');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (20, 'Asuriní do Tocantins');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (237, 'Parakanã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (4, 'Suruí do Pará/ Suruí do Tocantins/ Aikewara');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (21, 'Asuriní do Xingu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (22, 'Ava-Canoeiro/ Avá-Canoeiro, Avá, Canoeiro');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (37, 'Guajá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (266, 'Guaraní');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (38, 'Guaraní Kaiowá/ Guarani Kayová');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (39, 'Guaraní Mbyá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (40, 'Guaraní Nhandéva');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (52, 'Kaapor/ Urubu, Kaapór');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (267, 'Lingua De Sinais Kaapor/ Língua de Sinais Urubu-Kaapór');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (59, 'Kamayurá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (199, 'Amondáwa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (208, 'Diahói/ Diahui');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (215, 'Júma/ Juma');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (219, 'Karipúna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (268, 'Kawahíb');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (238, 'Parintintín');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (243, 'Tenharím/ Tenharim');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (76, 'Uru-Eu-Wau-Wau/ Uruewawau');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (80, 'Kayabí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (90, 'Kokáma');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (204, 'Kambéba');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (126, 'Lingua Geral Amazônica, Nheengatu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (151, 'Tapirapé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (211, 'Guajajára');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (155, 'Tembé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (269, 'Turiwára');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (183, 'Wayampí/ Oyampi');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (186, 'Xetá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (196, 'Zoé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (270, 'Tupí-Guaraní');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (250, 'Tupí, Tupi Antigo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (13, 'Apurinã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (60, 'Ashanínka/ Axanínka');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (26, 'Baníwa/ Tapiira Tapuya, Kawa Tapuya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (226, 'Kuripáko');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (29, 'Baré');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (145, 'Enawenê-Nawê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (271, 'Kaixána/ Kayuisiana');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (222, 'Kinikináu, Kinikinawa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (272, 'Machinéri');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (273, 'Mawayána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (109, 'Mehináku');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (131, 'Palikúr');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (133, 'Paresí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (152, 'Tariána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (156, 'Teréna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (179, 'Wapixána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (180, 'Warekéna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (182, 'Wauja/ Waurá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (193, 'Yawalapití');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (274, 'Aruák');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (10, 'Apalaí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (201, 'Arara do Pará, Arara do Xingu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (24, 'Bakairí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (35, 'Galibí do Oiapoque, Galibí (Karíña)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (43, 'Hixkaryána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (173, 'Ikpeng/ Ikpéng');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (45, 'Ingarikó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (58, 'Kalapálo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (94, 'Kuikúro');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (103, 'Matipú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (116, 'Nahukwá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (275, 'Naravúte');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (276, 'Kaxuyána/ Kahyána, Warikyána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (277, 'Xikuyána/ Sikiyána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (100, 'Makuxí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (218, 'Kapon Patamóna/ Kapon Ptamóna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (153, 'Taulipáng');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (167, 'Tiriyó/ Tarona');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (177, 'Wái Wái/ Waiwái');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (176, 'Waimirí-Atroarí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (184, 'Wayána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (108, 'Yekuána, Mayongong, Makiritáre,');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (278, 'Karib');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (15, 'Arara do Acre, Shawãdawa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (68, 'Katukína do Acre');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (77, 'Kaxararí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (78, 'Kaxinawá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (91, 'Korúbo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (279, 'Kulína Páno');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (102, 'Marúbo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (104, 'Matís');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (105, 'Matsés');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (389, 'Maya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (128, 'Nukiní');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (140, 'Poyanáwa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (246, 'Shanenáwa/ Xanenáwa, Xawanawa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (49, 'Yamináwa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (194, 'Yawanawá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (280, 'Pano');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (14, 'Arapáso');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (28, 'Bará');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (203, 'Barasána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (33, 'Desána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (64, 'Karapanã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (178, 'Wanána/ Guanána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (93, 'Kubéo, Kubewa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (281, 'Makúna, Yebá-masã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (282, 'Siriáno/ Suriana, Suriána');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (234, 'Tukáno / Miriti-Tapuia');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (172, 'Tuyúca / Tuyuca');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (216, 'Yurutí, Juriti');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (138, 'Piratapúya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (283, 'Arawá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (25, 'Banawá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (32, 'Dení');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (284, 'Himarimã/ Hi-merimã, Mirimã, Himarimá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (285, 'Jamamadí-Kanamanti/ Jamamadí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (48, 'Jarawára');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (95, 'Kulína Madijá/ Kulina, Kulína Madihá (Madija)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (136, 'Paumarí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (148, 'Zuruwahá, Suruahá (Zuruahá)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (61, 'Kanamarí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (69, 'Katukína');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (174, 'Tsohom Djapa/ Tsohondjapá (Tsohom Djapa)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (67, 'Katawixí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (34, 'Dâw');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (286, 'Hup, Húpda, Maku, Yuhupde, Yuhúp');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (115, 'Nadëb');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (287, 'Alaketesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (288, 'Alantesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (289, 'Hahaintesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (290, 'Halotesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (291, 'Kithaulú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (231, 'Mandúka/ Nambikwára do Campo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (292, 'Sararé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (300, 'Sawentesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (301, 'Waikisú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (302, 'Wakalitesú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (303, 'Wasusú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (228, 'Lakondê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (229, 'Latundê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (120, 'Negarotê/ Negarote');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (230, 'Mamaindê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (242, 'Tawandê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (143, 'Sabanê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (304, 'Nambikwára');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (225, 'Kujubím');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (305, 'Miguelénho/ Migueleno, Miguelenho');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (130, 'Oro Win');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (168, 'Torá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (175, 'Urupá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (245, 'Pakaá Nóva/Migueleno, Miguelenho');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (306, 'Txapakúra');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (127, 'Ninám');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (146, 'Sanumá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (190, 'Yanomám/ Yanonmán');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (191, 'Yanomámi');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (307, 'Bóra');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (233, 'Miránha');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (53, 'Kadiwéu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (308, 'Guaikurú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (113, 'Múra');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (137, 'Pirahã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (206, 'Chamakóko/ Samúko, Chamacoco');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (207, 'Chiquitáno/ Chiquito');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (18, 'Arikapú/ Jabutí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (47, 'Djeoromitxí/ Jabotí/ Jabutí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (309, 'Witóto');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (1, 'Aikaná/ Aikanã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (46, 'Irántxe');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (114, 'Mynky/ Mynký, Meky, Menky, Menki');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (227, 'Kwazá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (62, 'Kanoé/ Kanoê');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (157, 'Tikúna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (169, 'Trumái');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (135, 'Galibí Marwórno/ Galibi Marworno');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (134, 'Karipúna do Amapá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (310, 'Acona/ Akona');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (311, 'Aimoré');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (312, 'Anacé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (313, 'Apolima - Arara');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (314, 'Arana');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (315, 'Arapiun');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (316, 'Arikén');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (317, 'Arikose');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (318, 'Atikum');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (319, 'Awi');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (320, 'Baenã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (321, 'Borari');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (322, 'Botocudo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (323, 'Catokin (Katukína)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (324, 'Charrúa/ Charrua');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (325, 'Coiupanka');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (326, 'Guara');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (327, 'Guarino');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (328, 'Guaru');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (329, 'Isse');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (330, 'Jaricuna');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (331, 'Jeripancó/ Jeripankó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (332, 'Kaete');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (333, 'Kaimbé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (334, 'Kalabassa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (335, 'Kalankó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (336, 'Kamba/ Kámba');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (337, 'Kambiwá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (338, 'Kambiwá Pipipã');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (339, 'Kanindé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (340, 'Kantaruré');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (341, 'Kapinawá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (342, 'Karapoto/ Karapotó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (343, 'Karijo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (344, 'Kariri/ Karirí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (345, 'Kariri - Xocó/ Karirí-Xocó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (346, 'Kaxixó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (347, 'Kayuisiana -(Kaixána)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (348, 'Kiriri');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (349, 'Kueskue');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (350, 'Manao/ Manáo');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (351, 'Maragua');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (352, 'Maytapu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (353, 'Mucurim');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (354, 'Nawa/ Náwa');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (355, 'Paiaku');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (356, 'Pankará');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (357, 'Pankararé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (358, 'Pankararú/ Pankarú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (359, 'Pankararú - Kalanko');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (360, 'Pankararú - Karuazu');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (361, 'Pankaru');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (362, 'Patxôhã/ Patxoha');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (363, 'Paumelenho');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (364, 'Piri-Piri/ Pirí-Pirí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (365, 'Pitaguari/ Pitaguarí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (366, 'Potiguara/ Potiguára');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (367, 'Puri/ Purí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (368, 'Sapará/ Sapara');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (369, 'Tabajara');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (370, 'Tapajós');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (371, 'Tapeba');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (372, 'Tapiuns/ Tapiun');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (373, 'Tapuía/ Tapúya');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (374, 'Tingui Botó/ Tinguí-Botó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (375, 'Tremembé');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (376, 'Truká');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (377, 'Tumbalalá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (378, 'Tupinambá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (379, 'Tupinambaraná');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (380, 'Tupiniquim');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (381, 'Tuxá');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (382, 'Waira');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (383, 'Waiána-Apalaí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (384, 'Wajuju/ Wajujú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (385, 'Wassú (Wasusú)');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (386, 'Xocó');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (387, 'Xucuru/ Xukurú');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (388, 'Xucuru - Kariri/ Xukurú-Karirí');
INSERT INTO modules.lingua_indigena_educacenso (id, lingua) VALUES (999, 'Outras Linguas Indigenas');