ALTER TABLE pmieducar.escola ADD COLUMN situacao_funcionamento integer default 1;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_administrativa integer default 3;
ALTER TABLE pmieducar.escola ADD COLUMN regulamentacao integer default 1;
ALTER TABLE pmieducar.escola ADD COLUMN longitude varchar(20);
ALTER TABLE pmieducar.escola ADD COLUMN latitude varchar(20);
ALTER TABLE pmieducar.escola ADD COLUMN acesso integer;
ALTER TABLE pmieducar.escola ADD COLUMN ref_idpes_gestor integer;
ALTER TABLE pmieducar.escola ADD COLUMN cargo_gestor integer;
ALTER TABLE pmieducar.escola ADD COLUMN local_funcionamento integer;
ALTER TABLE pmieducar.escola ADD COLUMN condicao integer default 1;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada integer;
ALTER TABLE pmieducar.escola ADD COLUMN decreto_criacao varchar(50);
ALTER TABLE pmieducar.escola ADD COLUMN area_terreno_total varchar(10);
ALTER TABLE pmieducar.escola ADD COLUMN area_construida varchar(10);
ALTER TABLE pmieducar.escola ADD COLUMN area_disponivel varchar(10);
ALTER TABLE pmieducar.escola ADD COLUMN num_pavimentos integer;
ALTER TABLE pmieducar.escola ADD COLUMN tipo_piso integer;
ALTER TABLE pmieducar.escola ADD COLUMN medidor_energia integer;
ALTER TABLE pmieducar.escola ADD COLUMN agua_consumida integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_sala_diretoria integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_sala_professores integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_sala_secretaria integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_laboratorio_informatica integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_laboratorio_ciencias integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_sala_aee integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_quadra_coberta integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_quadra_descoberta integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_cozinha integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_biblioteca integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_sala_leitura integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_parque_infantil integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_bercario integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_banheiro_fora integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_banheiro_dentro integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_banheiro_infantil integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_banheiro_deficiente integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_banheiro_chuveiro integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_refeitorio integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_dispensa integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_aumoxarifado integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_auditorio integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_patio_coberto integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_patio_descoberto integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_alojamento_aluno integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_alojamento_professor integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_area_verde integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_lavanderia integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_unidade_climatizada integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_quantidade_ambiente_climatizado integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_nenhuma_relacionada integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_numero_salas_existente integer;
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_numero_salas_utilizadas integer;
ALTER TABLE pmieducar.escola ADD COLUMN porte_quadra_descoberta integer;
ALTER TABLE pmieducar.escola ADD COLUMN porte_quadra_coberta integer;
ALTER TABLE pmieducar.escola ADD COLUMN tipo_cobertura_patio integer;
ALTER TABLE pmieducar.escola ADD COLUMN total_funcionario integer;
ALTER TABLE pmieducar.escola ADD COLUMN atendimento_aee integer default 0;
ALTER TABLE pmieducar.escola ADD COLUMN atividade_complementar integer default 0;
ALTER TABLE pmieducar.escola ADD COLUMN fundamental_ciclo integer;
ALTER TABLE pmieducar.escola ADD COLUMN localizacao_diferenciada integer default 7;
ALTER TABLE pmieducar.escola ADD COLUMN didatico_nao_utiliza integer;
ALTER TABLE pmieducar.escola ADD COLUMN didatico_quilombola integer;
ALTER TABLE pmieducar.escola ADD COLUMN didatico_indigena integer;
ALTER TABLE pmieducar.escola ADD COLUMN educacao_indigena integer;
ALTER TABLE pmieducar.escola ADD COLUMN lingua_ministrada integer;
ALTER TABLE pmieducar.escola ADD COLUMN espaco_brasil_aprendizado integer;
ALTER TABLE pmieducar.escola ADD COLUMN abre_final_semana integer;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_lingua_indigena integer;
ALTER TABLE pmieducar.escola ADD COLUMN proposta_pedagogica integer;
ALTER TABLE pmieducar.escola ADD COLUMN televisoes smallint;
ALTER TABLE pmieducar.escola ADD COLUMN videocassetes smallint;
ALTER TABLE pmieducar.escola ADD COLUMN dvds smallint;
ALTER TABLE pmieducar.escola ADD COLUMN antenas_parabolicas smallint;
ALTER TABLE pmieducar.escola ADD COLUMN copiadoras smallint;
ALTER TABLE pmieducar.escola ADD COLUMN retroprojetores smallint;
ALTER TABLE pmieducar.escola ADD COLUMN impressoras smallint;
ALTER TABLE pmieducar.escola ADD COLUMN aparelhos_de_som smallint;
ALTER TABLE pmieducar.escola ADD COLUMN projetores_digitais smallint;
ALTER TABLE pmieducar.escola ADD COLUMN faxs smallint;
ALTER TABLE pmieducar.escola ADD COLUMN maquinas_fotograficas smallint;
ALTER TABLE pmieducar.escola ADD COLUMN computadores smallint;
ALTER TABLE pmieducar.escola ADD COLUMN computadores_administrativo smallint;
ALTER TABLE pmieducar.escola ADD COLUMN computadores_alunos smallint;
ALTER TABLE pmieducar.escola ADD COLUMN acesso_internet smallint;
ALTER TABLE pmieducar.escola ADD COLUMN ato_criacao varchar(255);
ALTER TABLE pmieducar.escola ADD COLUMN dependencia_vias_deficiente smallint;
ALTER TABLE pmieducar.escola ADD COLUMN utiliza_regra_diferenciada boolean;
ALTER TABLE pmieducar.escola ADD COLUMN ato_autorizativo varchar(255);
ALTER TABLE pmieducar.escola ADD COLUMN ref_idpes_secretario_escolar integer;
ALTER TABLE pmieducar.escola ADD COLUMN impressoras_multifuncionais smallint;
ALTER TABLE pmieducar.escola ADD COLUMN categoria_escola_privada integer;
ALTER TABLE pmieducar.escola ADD COLUMN conveniada_com_poder_publico integer;
ALTER TABLE pmieducar.escola ADD COLUMN cnpj_mantenedora_principal numeric(14);
ALTER TABLE pmieducar.escola ADD COLUMN mantenedora_escola_privada integer [];
ALTER TABLE pmieducar.escola ADD COLUMN materiais_didaticos_especificos integer;
ALTER TABLE pmieducar.escola ADD COLUMN abastecimento_agua integer [];
ALTER TABLE pmieducar.escola ADD COLUMN abastecimento_energia integer [];
ALTER TABLE pmieducar.escola ADD COLUMN esgoto_sanitario integer [];
ALTER TABLE pmieducar.escola ADD COLUMN destinacao_lixo integer [];
ALTER TABLE pmieducar.escola ADD COLUMN email_gestor varchar(255);
ALTER TABLE pmieducar.escola ADD COLUMN zona_localizacao smallint;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada2 integer;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada3 integer;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada4 integer;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada5 integer;
ALTER TABLE pmieducar.escola ADD COLUMN codigo_inep_escola_compartilhada6 integer;

alter table pmieducar.escola
	add constraint escola_ref_idpes_gestor_fk
		foreign key (ref_idpes_gestor) references cadastro.pessoa;

alter table pmieducar.escola
	add constraint escola_codigo_indigena_fk
		foreign key (codigo_lingua_indigena) references modules.lingua_indigena_educacenso;

alter table pmieducar.escola
	add constraint escola_ref_idpes_secretario_escolar_fkey
		foreign key (ref_idpes_secretario_escolar) references cadastro.pessoa;
