alter table pais
  add cod_ibge integer;

-- Atualiza todos os países
UPDATE public.pais SET nome = 'Abissínia', geom = null, cod_ibge = null WHERE idpais = 1;
UPDATE public.pais SET nome = 'Açores', geom = null, cod_ibge = null WHERE idpais = 2;
UPDATE public.pais SET nome = 'Afar Francês', geom = null, cod_ibge = null WHERE idpais = 3;
UPDATE public.pais SET nome = 'Afeganistão', geom = null, cod_ibge = 4 WHERE idpais = 4;
UPDATE public.pais SET nome = 'Albânia', geom = null, cod_ibge = 8 WHERE idpais = 5;
UPDATE public.pais SET nome = 'Alemanha', geom = null, cod_ibge = 276 WHERE idpais = 6;
UPDATE public.pais SET nome = 'Alto Volta', geom = null, cod_ibge = null WHERE idpais = 7;
UPDATE public.pais SET nome = 'Andorra', geom = null, cod_ibge = 20 WHERE idpais = 8;
UPDATE public.pais SET nome = 'Angola', geom = null, cod_ibge = 24 WHERE idpais = 9;
UPDATE public.pais SET nome = 'Antártica Francesa', geom = null, cod_ibge = null WHERE idpais = 10;
UPDATE public.pais SET nome = 'Antártico Argentino', geom = null, cod_ibge = null WHERE idpais = 11;
UPDATE public.pais SET nome = 'Antártico Britânico, Território', geom = null, cod_ibge = null WHERE idpais = 12;
UPDATE public.pais SET nome = 'Antártico Chileno', geom = null, cod_ibge = null WHERE idpais = 13;
UPDATE public.pais SET nome = 'Antártico Noruegues', geom = null, cod_ibge = null WHERE idpais = 14;
UPDATE public.pais SET nome = 'Antígua E. Dep. Barbuda', geom = null, cod_ibge = null WHERE idpais = 15;
UPDATE public.pais SET nome = 'Antilhas Holandesas', geom = null, cod_ibge = 530 WHERE idpais = 16;
UPDATE public.pais SET nome = 'Apátrida', geom = null, cod_ibge = 339 WHERE idpais = 17;
UPDATE public.pais SET nome = 'Arábia Saudita', geom = null, cod_ibge = 682 WHERE idpais = 18;
UPDATE public.pais SET nome = 'Argélia', geom = null, cod_ibge = 12 WHERE idpais = 19;
UPDATE public.pais SET nome = 'Argentina', geom = null, cod_ibge = 32 WHERE idpais = 20;
UPDATE public.pais SET nome = 'Armênia', geom = null, cod_ibge = 51 WHERE idpais = 21;
UPDATE public.pais SET nome = 'Arquipélago de Bismark', geom = null, cod_ibge = null WHERE idpais = 22;
UPDATE public.pais SET nome = 'Arquipélago Manahiki', geom = null, cod_ibge = null WHERE idpais = 23;
UPDATE public.pais SET nome = 'Arquipélago Midway', geom = null, cod_ibge = null WHERE idpais = 24;
UPDATE public.pais SET nome = 'Aruba', geom = null, cod_ibge = 533 WHERE idpais = 25;
UPDATE public.pais SET nome = 'Ascensão e Tristão da Cunha,is', geom = null, cod_ibge = null WHERE idpais = 26;
UPDATE public.pais SET nome = 'Ashmore e Cartier', geom = null, cod_ibge = null WHERE idpais = 27;
UPDATE public.pais SET nome = 'Austrália', geom = null, cod_ibge = 36 WHERE idpais = 28;
UPDATE public.pais SET nome = 'áustria', geom = null, cod_ibge = 40 WHERE idpais = 29;
UPDATE public.pais SET nome = 'Azerbaijão', geom = null, cod_ibge = 31 WHERE idpais = 30;
UPDATE public.pais SET nome = 'Bahrein', geom = null, cod_ibge = 48 WHERE idpais = 31;
UPDATE public.pais SET nome = 'Bangladesh', geom = null, cod_ibge = 50 WHERE idpais = 32;
UPDATE public.pais SET nome = 'Barbados', geom = null, cod_ibge = 52 WHERE idpais = 33;
UPDATE public.pais SET nome = 'Bashkista', geom = null, cod_ibge = null WHERE idpais = 34;
UPDATE public.pais SET nome = 'Bechuanalândia', geom = null, cod_ibge = null WHERE idpais = 35;
UPDATE public.pais SET nome = 'Bélgica', geom = null, cod_ibge = 56 WHERE idpais = 36;
UPDATE public.pais SET nome = 'Belize', geom = null, cod_ibge = 84 WHERE idpais = 37;
UPDATE public.pais SET nome = 'Benin', geom = null, cod_ibge = null WHERE idpais = 38;
UPDATE public.pais SET nome = 'Bermudas', geom = null, cod_ibge = 60 WHERE idpais = 39;
UPDATE public.pais SET nome = 'Bhutan', geom = null, cod_ibge = null WHERE idpais = 40;
UPDATE public.pais SET nome = 'Birmânia', geom = null, cod_ibge = null WHERE idpais = 41;
UPDATE public.pais SET nome = 'Bolívia', geom = null, cod_ibge = 68 WHERE idpais = 42;
UPDATE public.pais SET nome = 'Bósnia Herzegovina', geom = null, cod_ibge = null WHERE idpais = 43;
UPDATE public.pais SET nome = 'Botsuana', geom = null, cod_ibge = null WHERE idpais = 44;
UPDATE public.pais SET nome = 'Brasil', geom = null, cod_ibge = 76 WHERE idpais = 45;
UPDATE public.pais SET nome = 'Brunei', geom = null, cod_ibge = 96 WHERE idpais = 46;
UPDATE public.pais SET nome = 'Bulgária', geom = null, cod_ibge = 100 WHERE idpais = 47;
UPDATE public.pais SET nome = 'Burkina Fasso', geom = null, cod_ibge = null WHERE idpais = 48;
UPDATE public.pais SET nome = 'Burundi', geom = null, cod_ibge = 108 WHERE idpais = 49;
UPDATE public.pais SET nome = 'Buryat', geom = null, cod_ibge = null WHERE idpais = 50;
UPDATE public.pais SET nome = 'Cabo Verde', geom = null, cod_ibge = 132 WHERE idpais = 51;
UPDATE public.pais SET nome = 'Camarões', geom = null, cod_ibge = 120 WHERE idpais = 52;
UPDATE public.pais SET nome = 'Canadá', geom = null, cod_ibge = 124 WHERE idpais = 53;
UPDATE public.pais SET nome = 'Carélia', geom = null, cod_ibge = null WHERE idpais = 54;
UPDATE public.pais SET nome = 'Catar', geom = null, cod_ibge = 634 WHERE idpais = 55;
UPDATE public.pais SET nome = 'Cazaquistão', geom = null, cod_ibge = 398 WHERE idpais = 56;
UPDATE public.pais SET nome = 'Ceilão', geom = null, cod_ibge = null WHERE idpais = 57;
UPDATE public.pais SET nome = 'Ceuta e Melilla', geom = null, cod_ibge = null WHERE idpais = 58;
UPDATE public.pais SET nome = 'Chade', geom = null, cod_ibge = 148 WHERE idpais = 59;
UPDATE public.pais SET nome = 'Chechen Ingusth', geom = null, cod_ibge = null WHERE idpais = 60;
UPDATE public.pais SET nome = 'Chile', geom = null, cod_ibge = 152 WHERE idpais = 61;
UPDATE public.pais SET nome = 'China', geom = null, cod_ibge = 156 WHERE idpais = 62;
UPDATE public.pais SET nome = 'China (taiwan)', geom = null, cod_ibge = null WHERE idpais = 63;
UPDATE public.pais SET nome = 'Chipre', geom = null, cod_ibge = 196 WHERE idpais = 64;
UPDATE public.pais SET nome = 'Chuvash', geom = null, cod_ibge = null WHERE idpais = 65;
UPDATE public.pais SET nome = 'Cingapura', geom = null, cod_ibge = 702 WHERE idpais = 66;
UPDATE public.pais SET nome = 'Colômbia', geom = null, cod_ibge = 170 WHERE idpais = 67;
UPDATE public.pais SET nome = 'Comunidade das Bahamas', geom = null, cod_ibge = null WHERE idpais = 68;
UPDATE public.pais SET nome = 'Comunidade Dominicana', geom = null, cod_ibge = null WHERE idpais = 69;
UPDATE public.pais SET nome = 'Congo', geom = null, cod_ibge = null WHERE idpais = 70;
UPDATE public.pais SET nome = 'Coréia', geom = null, cod_ibge = null WHERE idpais = 71;
UPDATE public.pais SET nome = 'Costa do Marfim', geom = null, cod_ibge = 384 WHERE idpais = 72;
UPDATE public.pais SET nome = 'Costa Rica', geom = null, cod_ibge = 188 WHERE idpais = 73;
UPDATE public.pais SET nome = 'Coveite', geom = null, cod_ibge = null WHERE idpais = 74;
UPDATE public.pais SET nome = 'Croácia', geom = null, cod_ibge = 191 WHERE idpais = 75;
UPDATE public.pais SET nome = 'Cuba', geom = null, cod_ibge = 192 WHERE idpais = 76;
UPDATE public.pais SET nome = 'Curaçao', geom = null, cod_ibge = 531 WHERE idpais = 77;
UPDATE public.pais SET nome = 'Dagesta', geom = null, cod_ibge = null WHERE idpais = 78;
UPDATE public.pais SET nome = 'Daomé', geom = null, cod_ibge = null WHERE idpais = 79;
UPDATE public.pais SET nome = 'Dependência de Ross', geom = null, cod_ibge = null WHERE idpais = 80;
UPDATE public.pais SET nome = 'Dinamarca', geom = null, cod_ibge = 208 WHERE idpais = 81;
UPDATE public.pais SET nome = 'Djibuti', geom = null, cod_ibge = null WHERE idpais = 82;
UPDATE public.pais SET nome = 'Eire', geom = null, cod_ibge = null WHERE idpais = 83;
UPDATE public.pais SET nome = 'Emirados árabes Unidos', geom = null, cod_ibge = 784 WHERE idpais = 84;
UPDATE public.pais SET nome = 'Equador', geom = null, cod_ibge = 218 WHERE idpais = 85;
UPDATE public.pais SET nome = 'Escócia', geom = null, cod_ibge = null WHERE idpais = 86;
UPDATE public.pais SET nome = 'Eslováquia', geom = null, cod_ibge = 703 WHERE idpais = 87;
UPDATE public.pais SET nome = 'Eslovênia', geom = null, cod_ibge = 705 WHERE idpais = 88;
UPDATE public.pais SET nome = 'Espanha', geom = null, cod_ibge = 724 WHERE idpais = 89;
UPDATE public.pais SET nome = 'Estado da Cidade do Vaticano', geom = null, cod_ibge = null WHERE idpais = 90;
UPDATE public.pais SET nome = 'Estados Assoc. das Antilhas', geom = null, cod_ibge = null WHERE idpais = 91;
UPDATE public.pais SET nome = 'Estados Unidos da América (eua)', geom = null, cod_ibge = 840 WHERE idpais = 92;
UPDATE public.pais SET nome = 'Estônia', geom = null, cod_ibge = 233 WHERE idpais = 93;
UPDATE public.pais SET nome = 'Etiópia', geom = null, cod_ibge = 231 WHERE idpais = 94;
UPDATE public.pais SET nome = 'Filipinas', geom = null, cod_ibge = 608 WHERE idpais = 95;
UPDATE public.pais SET nome = 'Finlândia', geom = null, cod_ibge = 246 WHERE idpais = 96;
UPDATE public.pais SET nome = 'França', geom = null, cod_ibge = 250 WHERE idpais = 97;
UPDATE public.pais SET nome = 'Gâmbia', geom = null, cod_ibge = 270 WHERE idpais = 98;
UPDATE public.pais SET nome = 'Gana', geom = null, cod_ibge = 288 WHERE idpais = 99;
UPDATE public.pais SET nome = 'Gaza', geom = null, cod_ibge = null WHERE idpais = 100;
UPDATE public.pais SET nome = 'Geórgia', geom = null, cod_ibge = 268 WHERE idpais = 101;
UPDATE public.pais SET nome = 'Gibraltar', geom = null, cod_ibge = 292 WHERE idpais = 102;
UPDATE public.pais SET nome = 'Gorno Altai', geom = null, cod_ibge = null WHERE idpais = 103;
UPDATE public.pais SET nome = 'Grã-bretanha', geom = null, cod_ibge = null WHERE idpais = 104;
UPDATE public.pais SET nome = 'Granada', geom = null, cod_ibge = 308 WHERE idpais = 105;
UPDATE public.pais SET nome = 'Grécia', geom = null, cod_ibge = 300 WHERE idpais = 106;
UPDATE public.pais SET nome = 'Groenlândia', geom = null, cod_ibge = 304 WHERE idpais = 107;
UPDATE public.pais SET nome = 'Guam', geom = null, cod_ibge = 316 WHERE idpais = 108;
UPDATE public.pais SET nome = 'Guatemala', geom = null, cod_ibge = 320 WHERE idpais = 109;
UPDATE public.pais SET nome = 'Guiana Francesa', geom = null, cod_ibge = null WHERE idpais = 110;
UPDATE public.pais SET nome = 'Guiné', geom = null, cod_ibge = 324 WHERE idpais = 111;
UPDATE public.pais SET nome = 'Guiné Bissau', geom = null, cod_ibge = null WHERE idpais = 112;
UPDATE public.pais SET nome = 'Guiné Equatorial', geom = null, cod_ibge = 226 WHERE idpais = 113;
UPDATE public.pais SET nome = 'Holanda', geom = null, cod_ibge = 528 WHERE idpais = 114;
UPDATE public.pais SET nome = 'Honduras', geom = null, cod_ibge = 340 WHERE idpais = 115;
UPDATE public.pais SET nome = 'Honduras Britânicas', geom = null, cod_ibge = null WHERE idpais = 116;
UPDATE public.pais SET nome = 'Hong-kong', geom = null, cod_ibge = null WHERE idpais = 117;
UPDATE public.pais SET nome = 'Hungria', geom = null, cod_ibge = 348 WHERE idpais = 118;
UPDATE public.pais SET nome = 'Iemen', geom = null, cod_ibge = null WHERE idpais = 119;
UPDATE public.pais SET nome = 'Iemen do Sul', geom = null, cod_ibge = null WHERE idpais = 120;
UPDATE public.pais SET nome = 'Ifni', geom = null, cod_ibge = null WHERE idpais = 121;
UPDATE public.pais SET nome = 'Ilha Johnston e Sand', geom = null, cod_ibge = null WHERE idpais = 122;
UPDATE public.pais SET nome = 'Ilha Milhos', geom = null, cod_ibge = null WHERE idpais = 123;
UPDATE public.pais SET nome = 'Ilhas Baker', geom = null, cod_ibge = null WHERE idpais = 124;
UPDATE public.pais SET nome = 'Ilhas Baleares', geom = null, cod_ibge = null WHERE idpais = 125;
UPDATE public.pais SET nome = 'Ilhas Canárias', geom = null, cod_ibge = null WHERE idpais = 126;
UPDATE public.pais SET nome = 'Ilhas Cantão e Enderburg', geom = null, cod_ibge = null WHERE idpais = 127;
UPDATE public.pais SET nome = 'Ilhas Carolinas', geom = null, cod_ibge = null WHERE idpais = 128;
UPDATE public.pais SET nome = 'Ilhas Christmas', geom = null, cod_ibge = null WHERE idpais = 129;
UPDATE public.pais SET nome = 'Ilhas Comores', geom = null, cod_ibge = null WHERE idpais = 130;
UPDATE public.pais SET nome = 'Ilhas Cook', geom = null, cod_ibge = 184 WHERE idpais = 131;
UPDATE public.pais SET nome = 'Ilhas Cosmoledo (lomores)', geom = null, cod_ibge = null WHERE idpais = 132;
UPDATE public.pais SET nome = 'Ilhas de Man', geom = null, cod_ibge = null WHERE idpais = 133;
UPDATE public.pais SET nome = 'Ilhas do Canal', geom = null, cod_ibge = 830 WHERE idpais = 134;
UPDATE public.pais SET nome = 'Ilhas do Pacífico', geom = null, cod_ibge = null WHERE idpais = 135;
UPDATE public.pais SET nome = 'Ilhas Falklands', geom = null, cod_ibge = null WHERE idpais = 136;
UPDATE public.pais SET nome = 'Ilhas Faroes', geom = null, cod_ibge = null WHERE idpais = 137;
UPDATE public.pais SET nome = 'Ilhas Gilbert', geom = null, cod_ibge = null WHERE idpais = 138;
UPDATE public.pais SET nome = 'Ilhas Guadalupe', geom = null, cod_ibge = null WHERE idpais = 139;
UPDATE public.pais SET nome = 'Ilhas Howland e Jarvis', geom = null, cod_ibge = null WHERE idpais = 140;
UPDATE public.pais SET nome = 'Ilhas Kingman Reef', geom = null, cod_ibge = null WHERE idpais = 141;
UPDATE public.pais SET nome = 'Ilhas Linha', geom = null, cod_ibge = null WHERE idpais = 142;
UPDATE public.pais SET nome = 'Ilhas Macdonal e Heard', geom = null, cod_ibge = null WHERE idpais = 143;
UPDATE public.pais SET nome = 'Ilhas Macquaire', geom = null, cod_ibge = null WHERE idpais = 144;
UPDATE public.pais SET nome = 'Ilhas Malvinas', geom = null, cod_ibge = 238 WHERE idpais = 145;
UPDATE public.pais SET nome = 'Ilhas Marianas', geom = null, cod_ibge = null WHERE idpais = 146;
UPDATE public.pais SET nome = 'Ilhas Marshall', geom = null, cod_ibge = 584 WHERE idpais = 147;
UPDATE public.pais SET nome = 'Ilhas Niue', geom = null, cod_ibge = null WHERE idpais = 148;
UPDATE public.pais SET nome = 'Ilhas Norfolk', geom = null, cod_ibge = null WHERE idpais = 149;
UPDATE public.pais SET nome = 'Ilhas Nova Caledônia', geom = null, cod_ibge = null WHERE idpais = 150;
UPDATE public.pais SET nome = 'Ilhas Novas Hebridas', geom = null, cod_ibge = null WHERE idpais = 151;
UPDATE public.pais SET nome = 'Ilhas Palau', geom = null, cod_ibge = null WHERE idpais = 152;
UPDATE public.pais SET nome = 'Ilhas Páscoa', geom = null, cod_ibge = null WHERE idpais = 153;
UPDATE public.pais SET nome = 'Ilhas Pitcairin', geom = null, cod_ibge = null WHERE idpais = 154;
UPDATE public.pais SET nome = 'Ilhas Salomão', geom = null, cod_ibge = 90 WHERE idpais = 155;
UPDATE public.pais SET nome = 'Ilhas Santa Cruz', geom = null, cod_ibge = null WHERE idpais = 156;
UPDATE public.pais SET nome = 'Ilhas Serranas', geom = null, cod_ibge = null WHERE idpais = 157;
UPDATE public.pais SET nome = 'Ilhas Tokelau', geom = null, cod_ibge = null WHERE idpais = 158;
UPDATE public.pais SET nome = 'Ilhas Turca', geom = null, cod_ibge = null WHERE idpais = 159;
UPDATE public.pais SET nome = 'Ilhas Turks e Caicos', geom = null, cod_ibge = null WHERE idpais = 160;
UPDATE public.pais SET nome = 'Ilhas Virgens Americanas', geom = null, cod_ibge = 850 WHERE idpais = 161;
UPDATE public.pais SET nome = 'Ilhas Virgens Britânicas', geom = null, cod_ibge = 92 WHERE idpais = 162;
UPDATE public.pais SET nome = 'Ilhas Wake', geom = null, cod_ibge = null WHERE idpais = 163;
UPDATE public.pais SET nome = 'Ilhas Wallis e Futuna', geom = null, cod_ibge = null WHERE idpais = 164;
UPDATE public.pais SET nome = 'índia', geom = null, cod_ibge = null WHERE idpais = 165;
UPDATE public.pais SET nome = 'Indonésia', geom = null, cod_ibge = 360 WHERE idpais = 166;
UPDATE public.pais SET nome = 'Inglaterra', geom = null, cod_ibge = null WHERE idpais = 167;
UPDATE public.pais SET nome = 'Irã', geom = null, cod_ibge = 364 WHERE idpais = 168;
UPDATE public.pais SET nome = 'Iraque', geom = null, cod_ibge = 368 WHERE idpais = 169;
UPDATE public.pais SET nome = 'Irlanda', geom = null, cod_ibge = 372 WHERE idpais = 170;
UPDATE public.pais SET nome = 'Irlanda do Norte', geom = null, cod_ibge = null WHERE idpais = 171;
UPDATE public.pais SET nome = 'Islândia', geom = null, cod_ibge = 352 WHERE idpais = 172;
UPDATE public.pais SET nome = 'Israel', geom = null, cod_ibge = 376 WHERE idpais = 173;
UPDATE public.pais SET nome = 'Itália', geom = null, cod_ibge = 380 WHERE idpais = 174;
UPDATE public.pais SET nome = 'Iugoslávia', geom = null, cod_ibge = null WHERE idpais = 175;
UPDATE public.pais SET nome = 'Jamaica', geom = null, cod_ibge = 388 WHERE idpais = 176;
UPDATE public.pais SET nome = 'Japão', geom = null, cod_ibge = 392 WHERE idpais = 177;
UPDATE public.pais SET nome = 'Jordânia', geom = null, cod_ibge = 400 WHERE idpais = 178;
UPDATE public.pais SET nome = 'Kabardino Balkar', geom = null, cod_ibge = null WHERE idpais = 179;
UPDATE public.pais SET nome = 'Kalimatan', geom = null, cod_ibge = null WHERE idpais = 180;
UPDATE public.pais SET nome = 'Kalmir', geom = null, cod_ibge = null WHERE idpais = 181;
UPDATE public.pais SET nome = 'Kara Kalpak', geom = null, cod_ibge = null WHERE idpais = 182;
UPDATE public.pais SET nome = 'Karachaevocherkess', geom = null, cod_ibge = null WHERE idpais = 183;
UPDATE public.pais SET nome = 'Khakass', geom = null, cod_ibge = null WHERE idpais = 184;
UPDATE public.pais SET nome = 'Kmer/camboja', geom = null, cod_ibge = null WHERE idpais = 185;
UPDATE public.pais SET nome = 'Komi', geom = null, cod_ibge = null WHERE idpais = 186;
UPDATE public.pais SET nome = 'Kuwait', geom = null, cod_ibge = null WHERE idpais = 187;
UPDATE public.pais SET nome = 'Laos', geom = null, cod_ibge = 418 WHERE idpais = 188;
UPDATE public.pais SET nome = 'Lesoto', geom = null, cod_ibge = 426 WHERE idpais = 189;
UPDATE public.pais SET nome = 'Letônia', geom = null, cod_ibge = null WHERE idpais = 190;
UPDATE public.pais SET nome = 'Líbano', geom = null, cod_ibge = 422 WHERE idpais = 191;
UPDATE public.pais SET nome = 'Libéria', geom = null, cod_ibge = 430 WHERE idpais = 192;
UPDATE public.pais SET nome = 'Líbia', geom = null, cod_ibge = 434 WHERE idpais = 193;
UPDATE public.pais SET nome = 'Liechtenstein', geom = null, cod_ibge = 438 WHERE idpais = 194;
UPDATE public.pais SET nome = 'Lituânia', geom = null, cod_ibge = 440 WHERE idpais = 195;
UPDATE public.pais SET nome = 'Luxemburgo', geom = null, cod_ibge = 442 WHERE idpais = 196;
UPDATE public.pais SET nome = 'Macau', geom = null, cod_ibge = 446 WHERE idpais = 197;
UPDATE public.pais SET nome = 'Madagascar', geom = null, cod_ibge = null WHERE idpais = 198;
UPDATE public.pais SET nome = 'Madeira', geom = null, cod_ibge = null WHERE idpais = 199;
UPDATE public.pais SET nome = 'Malásia', geom = null, cod_ibge = 458 WHERE idpais = 200;
UPDATE public.pais SET nome = 'Malawi', geom = null, cod_ibge = 454 WHERE idpais = 201;
UPDATE public.pais SET nome = 'Maldivas,is', geom = null, cod_ibge = null WHERE idpais = 202;
UPDATE public.pais SET nome = 'Mali', geom = null, cod_ibge = 466 WHERE idpais = 203;
UPDATE public.pais SET nome = 'Mari', geom = null, cod_ibge = null WHERE idpais = 204;
UPDATE public.pais SET nome = 'Marrocos', geom = null, cod_ibge = 504 WHERE idpais = 205;
UPDATE public.pais SET nome = 'Martinica', geom = null, cod_ibge = 474 WHERE idpais = 206;
UPDATE public.pais SET nome = 'Mascate', geom = null, cod_ibge = null WHERE idpais = 207;
UPDATE public.pais SET nome = 'Maurício', geom = null, cod_ibge = null WHERE idpais = 208;
UPDATE public.pais SET nome = 'Mauritânia', geom = null, cod_ibge = 478 WHERE idpais = 209;
UPDATE public.pais SET nome = 'México', geom = null, cod_ibge = 484 WHERE idpais = 210;
UPDATE public.pais SET nome = 'Mianma', geom = null, cod_ibge = null WHERE idpais = 211;
UPDATE public.pais SET nome = 'Moçambique', geom = null, cod_ibge = 508 WHERE idpais = 212;
UPDATE public.pais SET nome = 'Moldávia', geom = null, cod_ibge = 498 WHERE idpais = 213;
UPDATE public.pais SET nome = 'Mônaco', geom = null, cod_ibge = 492 WHERE idpais = 214;
UPDATE public.pais SET nome = 'Mongólia', geom = null, cod_ibge = 496 WHERE idpais = 215;
UPDATE public.pais SET nome = 'Monte Serrat', geom = null, cod_ibge = null WHERE idpais = 216;
UPDATE public.pais SET nome = 'Montenegro', geom = null, cod_ibge = 499 WHERE idpais = 217;
UPDATE public.pais SET nome = 'Namíbia', geom = null, cod_ibge = 516 WHERE idpais = 218;
UPDATE public.pais SET nome = 'Nauru', geom = null, cod_ibge = 520 WHERE idpais = 219;
UPDATE public.pais SET nome = 'Nepal', geom = null, cod_ibge = 524 WHERE idpais = 220;
UPDATE public.pais SET nome = 'Nguane', geom = null, cod_ibge = null WHERE idpais = 221;
UPDATE public.pais SET nome = 'Nicarágua', geom = null, cod_ibge = 558 WHERE idpais = 222;
UPDATE public.pais SET nome = 'Nigéria', geom = null, cod_ibge = 566 WHERE idpais = 223;
UPDATE public.pais SET nome = 'Noruega', geom = null, cod_ibge = 578 WHERE idpais = 224;
UPDATE public.pais SET nome = 'Nova Guiné', geom = null, cod_ibge = null WHERE idpais = 225;
UPDATE public.pais SET nome = 'Nova Zelândia', geom = null, cod_ibge = 554 WHERE idpais = 226;
UPDATE public.pais SET nome = 'Oman', geom = null, cod_ibge = null WHERE idpais = 227;
UPDATE public.pais SET nome = 'Ossetia Setentrional', geom = null, cod_ibge = null WHERE idpais = 228;
UPDATE public.pais SET nome = 'País de Gales', geom = null, cod_ibge = null WHERE idpais = 229;
UPDATE public.pais SET nome = 'Países Baixos', geom = null, cod_ibge = null WHERE idpais = 230;
UPDATE public.pais SET nome = 'Palestina', geom = null, cod_ibge = 275 WHERE idpais = 231;
UPDATE public.pais SET nome = 'Panamá', geom = null, cod_ibge = 591 WHERE idpais = 232;
UPDATE public.pais SET nome = 'Panamá - Zona do Canal', geom = null, cod_ibge = null WHERE idpais = 233;
UPDATE public.pais SET nome = 'Papua Nova Guiné', geom = null, cod_ibge = null WHERE idpais = 234;
UPDATE public.pais SET nome = 'Paquistão', geom = null, cod_ibge = 586 WHERE idpais = 235;
UPDATE public.pais SET nome = 'Paraguai', geom = null, cod_ibge = 600 WHERE idpais = 236;
UPDATE public.pais SET nome = 'Peru', geom = null, cod_ibge = 604 WHERE idpais = 237;
UPDATE public.pais SET nome = 'Polinésia Francesa', geom = null, cod_ibge = 258 WHERE idpais = 238;
UPDATE public.pais SET nome = 'Polônia', geom = null, cod_ibge = 616 WHERE idpais = 239;
UPDATE public.pais SET nome = 'Porto Rico', geom = null, cod_ibge = 630 WHERE idpais = 240;
UPDATE public.pais SET nome = 'Portugal', geom = null, cod_ibge = 620 WHERE idpais = 241;
UPDATE public.pais SET nome = 'Praças Norte Africanas', geom = null, cod_ibge = null WHERE idpais = 242;
UPDATE public.pais SET nome = 'Protetor do Sudoeste Africano', geom = null, cod_ibge = null WHERE idpais = 243;
UPDATE public.pais SET nome = 'Quênia', geom = null, cod_ibge = null WHERE idpais = 244;
UPDATE public.pais SET nome = 'Quirguistão', geom = null, cod_ibge = null WHERE idpais = 245;
UPDATE public.pais SET nome = 'Quitasueno', geom = null, cod_ibge = null WHERE idpais = 246;
UPDATE public.pais SET nome = 'República árabe do Egito', geom = null, cod_ibge = null WHERE idpais = 247;
UPDATE public.pais SET nome = 'República Centro Africana', geom = null, cod_ibge = null WHERE idpais = 248;
UPDATE public.pais SET nome = 'República da áfrica do Sul', geom = null, cod_ibge = null WHERE idpais = 249;
UPDATE public.pais SET nome = 'República da Bielorrússia', geom = null, cod_ibge = null WHERE idpais = 250;
UPDATE public.pais SET nome = 'República da Macedônia', geom = null, cod_ibge = null WHERE idpais = 251;
UPDATE public.pais SET nome = 'República de El Salvador', geom = null, cod_ibge = null WHERE idpais = 252;
UPDATE public.pais SET nome = 'República de Fiji', geom = null, cod_ibge = null WHERE idpais = 253;
UPDATE public.pais SET nome = 'República de Malta', geom = null, cod_ibge = null WHERE idpais = 254;
UPDATE public.pais SET nome = 'República do Gabão', geom = null, cod_ibge = null WHERE idpais = 255;
UPDATE public.pais SET nome = 'República do Haiti', geom = null, cod_ibge = null WHERE idpais = 256;
UPDATE public.pais SET nome = 'República do Níger', geom = null, cod_ibge = null WHERE idpais = 257;
UPDATE public.pais SET nome = 'República Dominicana', geom = null, cod_ibge = 214 WHERE idpais = 258;
UPDATE public.pais SET nome = 'República Guiana', geom = null, cod_ibge = null WHERE idpais = 259;
UPDATE public.pais SET nome = 'República Tcheca', geom = null, cod_ibge = 203 WHERE idpais = 260;
UPDATE public.pais SET nome = 'Reservado', geom = null, cod_ibge = null WHERE idpais = 261;
UPDATE public.pais SET nome = 'Reservado', geom = null, cod_ibge = null WHERE idpais = 262;
UPDATE public.pais SET nome = 'Reservado', geom = null, cod_ibge = null WHERE idpais = 263;
UPDATE public.pais SET nome = 'Reservado', geom = null, cod_ibge = null WHERE idpais = 264;
UPDATE public.pais SET nome = 'Reunião', geom = null, cod_ibge = null WHERE idpais = 265;
UPDATE public.pais SET nome = 'Rodésia (zimbábwe)', geom = null, cod_ibge = null WHERE idpais = 266;
UPDATE public.pais SET nome = 'Romênia', geom = null, cod_ibge = null WHERE idpais = 267;
UPDATE public.pais SET nome = 'Roncador', geom = null, cod_ibge = null WHERE idpais = 268;
UPDATE public.pais SET nome = 'Ruanda', geom = null, cod_ibge = 646 WHERE idpais = 269;
UPDATE public.pais SET nome = 'Ruiquiu,is', geom = null, cod_ibge = null WHERE idpais = 270;
UPDATE public.pais SET nome = 'Rússia', geom = null, cod_ibge = 643 WHERE idpais = 271;
UPDATE public.pais SET nome = 'Saara Espanhol', geom = null, cod_ibge = null WHERE idpais = 272;
UPDATE public.pais SET nome = 'Sabah', geom = null, cod_ibge = null WHERE idpais = 273;
UPDATE public.pais SET nome = 'Samoa Americana', geom = null, cod_ibge = 16 WHERE idpais = 274;
UPDATE public.pais SET nome = 'Samoa Ocidental', geom = null, cod_ibge = null WHERE idpais = 275;
UPDATE public.pais SET nome = 'San Marino', geom = null, cod_ibge = 674 WHERE idpais = 276;
UPDATE public.pais SET nome = 'Santa Helena', geom = null, cod_ibge = 654 WHERE idpais = 277;
UPDATE public.pais SET nome = 'Santa Lúcia', geom = null, cod_ibge = 662 WHERE idpais = 278;
UPDATE public.pais SET nome = 'São Cristóvão', geom = null, cod_ibge = null WHERE idpais = 279;
UPDATE public.pais SET nome = 'São Tomé e Príncipe', geom = null, cod_ibge = 678 WHERE idpais = 280;
UPDATE public.pais SET nome = 'São Vicente', geom = null, cod_ibge = null WHERE idpais = 281;
UPDATE public.pais SET nome = 'Sarawak', geom = null, cod_ibge = null WHERE idpais = 282;
UPDATE public.pais SET nome = 'Senegal', geom = null, cod_ibge = 686 WHERE idpais = 283;
UPDATE public.pais SET nome = 'Sequin', geom = null, cod_ibge = null WHERE idpais = 284;
UPDATE public.pais SET nome = 'Serra Leoa', geom = null, cod_ibge = 694 WHERE idpais = 285;
UPDATE public.pais SET nome = 'Sérvia', geom = null, cod_ibge = 688 WHERE idpais = 286;
UPDATE public.pais SET nome = 'Seychelles', geom = null, cod_ibge = null WHERE idpais = 287;
UPDATE public.pais SET nome = 'Síria', geom = null, cod_ibge = 760 WHERE idpais = 288;
UPDATE public.pais SET nome = 'Somália, República', geom = null, cod_ibge = null WHERE idpais = 289;
UPDATE public.pais SET nome = 'Sri-lanka', geom = null, cod_ibge = null WHERE idpais = 290;
UPDATE public.pais SET nome = 'St. Pierre et Miquelon', geom = null, cod_ibge = null WHERE idpais = 291;
UPDATE public.pais SET nome = 'Suazilândia', geom = null, cod_ibge = 748 WHERE idpais = 292;
UPDATE public.pais SET nome = 'Sudão', geom = null, cod_ibge = 729 WHERE idpais = 293;
UPDATE public.pais SET nome = 'Suécia', geom = null, cod_ibge = 752 WHERE idpais = 294;
UPDATE public.pais SET nome = 'Suíça', geom = null, cod_ibge = 756 WHERE idpais = 295;
UPDATE public.pais SET nome = 'Suriname', geom = null, cod_ibge = 740 WHERE idpais = 296;
UPDATE public.pais SET nome = 'Svalbard e Jan Mayer,is', geom = null, cod_ibge = null WHERE idpais = 297;
UPDATE public.pais SET nome = 'Tadjiquistão', geom = null, cod_ibge = null WHERE idpais = 298;
UPDATE public.pais SET nome = 'Tailândia', geom = null, cod_ibge = 764 WHERE idpais = 299;
UPDATE public.pais SET nome = 'Tanganica', geom = null, cod_ibge = null WHERE idpais = 300;
UPDATE public.pais SET nome = 'Tanzânia', geom = null, cod_ibge = 834 WHERE idpais = 301;
UPDATE public.pais SET nome = 'Tartaria', geom = null, cod_ibge = null WHERE idpais = 302;
UPDATE public.pais SET nome = 'Tchecoslováquia', geom = null, cod_ibge = null WHERE idpais = 303;
UPDATE public.pais SET nome = 'Terr. Antártico da Austrália', geom = null, cod_ibge = null WHERE idpais = 304;
UPDATE public.pais SET nome = 'Terras Austrais', geom = null, cod_ibge = null WHERE idpais = 305;
UPDATE public.pais SET nome = 'Territ. Britânico do Oceano índico', geom = null, cod_ibge = null WHERE idpais = 306;
UPDATE public.pais SET nome = 'Território de Cocos', geom = null, cod_ibge = null WHERE idpais = 307;
UPDATE public.pais SET nome = 'Território de Papua', geom = null, cod_ibge = null WHERE idpais = 308;
UPDATE public.pais SET nome = 'Timor', geom = null, cod_ibge = null WHERE idpais = 309;
UPDATE public.pais SET nome = 'Togo', geom = null, cod_ibge = 768 WHERE idpais = 310;
UPDATE public.pais SET nome = 'Tonga', geom = null, cod_ibge = 776 WHERE idpais = 311;
UPDATE public.pais SET nome = 'Transkei', geom = null, cod_ibge = null WHERE idpais = 312;
UPDATE public.pais SET nome = 'Trégua, Estado', geom = null, cod_ibge = null WHERE idpais = 313;
UPDATE public.pais SET nome = 'Trinidad e Tobago', geom = null, cod_ibge = 780 WHERE idpais = 314;
UPDATE public.pais SET nome = 'Tunísia', geom = null, cod_ibge = 788 WHERE idpais = 315;
UPDATE public.pais SET nome = 'Turcomenistão', geom = null, cod_ibge = 795 WHERE idpais = 316;
UPDATE public.pais SET nome = 'Turquia', geom = null, cod_ibge = 792 WHERE idpais = 317;
UPDATE public.pais SET nome = 'Tuvalu', geom = null, cod_ibge = 798 WHERE idpais = 318;
UPDATE public.pais SET nome = 'Tuvin', geom = null, cod_ibge = null WHERE idpais = 319;
UPDATE public.pais SET nome = 'Ucrânia', geom = null, cod_ibge = 804 WHERE idpais = 320;
UPDATE public.pais SET nome = 'Udmurt', geom = null, cod_ibge = null WHERE idpais = 321;
UPDATE public.pais SET nome = 'Uganda', geom = null, cod_ibge = 800 WHERE idpais = 322;
UPDATE public.pais SET nome = 'União Soviética', geom = null, cod_ibge = null WHERE idpais = 323;
UPDATE public.pais SET nome = 'Uruguai', geom = null, cod_ibge = 858 WHERE idpais = 324;
UPDATE public.pais SET nome = 'Uzbequistão', geom = null, cod_ibge = 860 WHERE idpais = 325;
UPDATE public.pais SET nome = 'Venezuela', geom = null, cod_ibge = 862 WHERE idpais = 326;
UPDATE public.pais SET nome = 'Vietnã do Norte', geom = null, cod_ibge = null WHERE idpais = 327;
UPDATE public.pais SET nome = 'Vietnã do Sul', geom = null, cod_ibge = null WHERE idpais = 328;
UPDATE public.pais SET nome = 'Yakut', geom = null, cod_ibge = null WHERE idpais = 329;
UPDATE public.pais SET nome = 'Zaire', geom = null, cod_ibge = null WHERE idpais = 330;
UPDATE public.pais SET nome = 'Zâmbia', geom = null, cod_ibge = 894 WHERE idpais = 331;
UPDATE public.pais SET nome = 'Zimbábwe', geom = null, cod_ibge = null WHERE idpais = 332;